### ISSUE TITLE
Implement configuration of additional field types

### ISSUE THREAD

**Issue by evelynchoukhie** [FAIMS/FAIMS3-Designer#16]
- [x] ActionButton => removed prototype
- [x] Checkbox => base
- [x] DateTimeNow
- [x] FileUploader => base
- [x] MapFormField
- [x] MultiSelect
- [x] RadioGroup
- [x] RandomStyle
- [x] **NEW** RichText => used MDXEditor for this
- [ ] AdvancedSelect
- [x] TakePhoto => base
- [x] TakePoint => base
- [x] QRCodeFormField => base (as far as I understand)
- [x] TemplatedStringField (complex)
- [x] BasicAutoIncrementer
- [x] RelatedRecordSelector

**Comment by stevecassidy** [comment]
New RichText field:

```
 {
    'component-namespace': 'faims-custom',
    'component-name': 'RichText',
    'type-returned': 'faims-core::String',
    'component-parameters': {
      label: 'Unused',
      content: 'Hello __World__',
    },
  };
```

**Comment by evelynchoukhie** [comment]
_(Probably needs to be opened as its own issue later.)_ 

I've run into a strange bug when replacing the Project Description field with the MDXEditor in the Info Panel. On initial load, the field does not pre-fill (see first screenshot). But when I change panels (e.g., go to Roles) and then come back to Info, the field is pre-filled with the correct content (see second screenshot).

<img width="1002" alt="image" src="https://github.com/FAIMS/FAIMS3-Designer/assets/100062745/ad799b8f-8083-47c0-905d-bddb66aada88">
<img width="1002" alt="image" src="https://github.com/FAIMS/FAIMS3-Designer/assets/100062745/f1dca2dc-b9f4-472b-aefc-f6e5506bd90d">
